spring:            
  profiles: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/restwithspring?createDatabaseIfNotExist=true
    username: restUser
    password: restmy5ql
  initialize: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect      
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  security:
           user:
            name: mayuran
            password: mayuran
           ignored: /**            
logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: INFO
    guru.springframework.controllers: INFO
    org.hibernate: INFO
    
  signing-key:  
        aasdssdasdadadsa
            
  

###
#   H2 Settings
###
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false
        
---

  spring:
    profiles: production
    server:
      port: 0
  